name: flutter_fritzapi
description: API for Fritz!Box, Fritz!DECT
version: 0.1.0
homepage: https://github.com/ehwplus/flutter_fritzapi

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  crypto: '>=3.0.2'
  flutter:
    sdk: flutter
  json_annotation: '>=4.9.0'

dev_dependencies:
  build_runner: '>=2.0.4'
  flutter_lints: '>=2.0.0'
  flutter_test:
    sdk: flutter
  json_serializable: ">=4.1.2"
  test: '>=1.16.8'